packages:
  - '.'
  - 'packages/*'

catalog:
  '@orpc/contract': ^1.9.3
  '@orpc/client': ^1.14.2
  '@orpc/openapi-client': ^1.14.2
  '@orpc/openapi': ^1.14.2
  '@orpc/server': ^1.14.2
  zod: ^4.1.11

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
